// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-JiaQ0RXoSUa9us1Zd_xwv3Mk_j9Xb4',
    appId: '1:162191643161:web:fb8ddf6ccb2f5dac8f9088',
    messagingSenderId: '162191643161',
    projectId: 'gracedominion-d5643',
    authDomain: 'gracedominion-d5643.firebaseapp.com',
    storageBucket: 'gracedominion-d5643.appspot.com',
    measurementId: 'G-HK8WESM16P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtSDS3QSQuWFLDbwdgpslZywRSXqot8g',
    appId: '1:162191643161:android:b891271550e9f5568f9088',
    messagingSenderId: '162191643161',
    projectId: 'gracedominion-d5643',
    storageBucket: 'gracedominion-d5643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQ_I13-VL_4VQR4bdp2P140BQuz2LjyE',
    appId: '1:162191643161:ios:8274aceb55eb32638f9088',
    messagingSenderId: '162191643161',
    projectId: 'gracedominion-d5643',
    storageBucket: 'gracedominion-d5643.appspot.com',
    iosClientId: '162191643161-itsnm9ps831rs5jjrpr3n9lhe007cqv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gracedominion',
  );
}
